---
- tasks:
    - name: Install Ruby on Fedora
        dnf: 
            name: "{{ beef_ruby }}"
            state: latest
        become: true

    - name: Clone BeEF
        git:
            repo: "git clone https://github.com/beefproject/beef"
            dest: /root/tools/beef 
            clone: yes
        become: true

    - name: Install BeEF
      shell: /root/tools/beef/install
      changed_when: false
      become: true

    - name: Create Symlink
      file:
          src: /root/tools/beef/beef
          dst: /bin/beef
          state: link
      become: true
